#!/bin/bash

# creation du dossier de reception
mkdir /home/HEB-TT/h_cmassieu/recup

# recuperation des images
input="/home/HEB-TT/h_cmassieu/a_parser"

while IFS= read -r line
do
        cp $line "/home/HEB-TT/h_cmassieu/recup/"

done < "$input"

# creation de l'archive
zip -r recup.zip /home/HEB-TT/h_cmassieu/recup/
